<div class="box">
	<div class="caption">Disease Management</div>
		<p><img alt="Enroll &mdash; and take Control" src="/images/body/enroll.gif" border="0" /><br />
Our Disease Management Programs provide online resources that help you manage your condition more effectively.<br />
<br />
Call <strong>1-800-392-4247</strong> to enroll or&nbsp;<a href="/heb/disease_man_programs.htm">click here</a>&nbsp;to learn more about how Disease Management Programs can help you.</p>
				
</div>

